package me.rerere.workspace

import java.io.File
import java.nio.file.Files

class RootfsPatcher {
    fun patch(
        linuxDir: File,
        options: RootfsPatchOptions = RootfsPatchOptions(),
    ) {
        val etcDir = File(linuxDir, "etc")
        if (!etcDir.isDirectory) return

        // patch 是幂等读改写, 参数未变时重复执行纯属浪费;
        // 每条 shell 命令都要走一次, 这里用 marker 记住已完成的参数集直接返回。
        val marker = File(etcDir, PATCH_MARKER)
        val signature = options.markerSignature()
        if (marker.isFile && marker.readText() == signature) return

        ensureRootfsDns(etcDir, options.nameservers)
        ensureHosts(etcDir, options.hostname)
        ensureHostname(etcDir, options.hostname)
        ensureLocale(etcDir, options.locale)
        ensureGroupNames(etcDir, options.groupIds.ifEmpty { currentSupplementaryGroupIds() })
        ensureAptMirror(etcDir)
        ensureTempDirs(linuxDir)
        marker.writeText(signature)
    }

    /**
     * 把 apt 源换成国内镜像。Ubuntu Base 的 sources.list 默认指向
     * archive.ubuntu.com / security.ubuntu.com，国内直连极慢，AI 装包（node/git 等）
     * 经常超时被当成「环境不可用」。默认 http 源，避免 base 镜像缺 ca-certificates
     * 时 https 源直接失效。只换主机名，保留路径结构（含 security 套件）。
     */
    private fun ensureAptMirror(etcDir: File) {
        val sourcesList = File(etcDir, "apt/sources.list")
        if (!sourcesList.isFile) return
        val original = sourcesList.readText()
        if (original.contains(APT_MIRROR_HOST)) return
        val patched = original
            .lineSequence()
            .joinToString("\n") { line ->
                val trimmed = line.trimStart()
                when {
                    trimmed.startsWith("#") || trimmed.isBlank() -> line
                    APT_OFFICIAL_HOSTS.any { line.contains(it) } ->
                        APT_OFFICIAL_HOSTS.fold(line) { acc, host ->
                            acc
                                .replace("http://$host", APT_MIRROR)
                                .replace("https://$host", APT_MIRROR)
                                // archive 路径已含 /ubuntu，折叠镜像基址后产生的重复段
                                .replace("ubuntu/ubuntu", "ubuntu")
                                // security 套件在镜像站也走 /ubuntu 路径
                                .replace("ubuntu-security", "ubuntu")
                        }
                    else -> line
                }
            }
        if (patched == original) return
        val backup = File(etcDir, "apt/sources.list.orig")
        if (!backup.exists()) {
            runCatching { sourcesList.copyTo(backup, overwrite = false) }
        }
        sourcesList.writeText(patched)
    }

    private fun ensureRootfsDns(
        etcDir: File,
        nameservers: List<String>,
    ) {
        val resolvConf = File(etcDir, "resolv.conf")
        val shouldWrite = when {
            Files.isSymbolicLink(resolvConf.toPath()) -> true
            !resolvConf.exists() -> true
            !resolvConf.isFile -> true
            else -> resolvConf.readText()
                .lineSequence()
                .filter { it.trimStart().startsWith("nameserver ") }
                .none { line ->
                    val server = line.trim().removePrefix("nameserver").trim()
                    server.isNotBlank() && server !in LOCAL_RESOLVERS
                }
        }
        if (!shouldWrite) return

        if (resolvConf.exists() || Files.isSymbolicLink(resolvConf.toPath())) {
            resolvConf.delete()
        }

        val servers = nameservers
            .filter { it.isNotBlank() }
            .distinct()
            .take(MAX_DNS_SERVERS)
            .ifEmpty { DEFAULT_DNS_SERVERS }

        resolvConf.writeText(
            buildString {
                appendLine("# Generated by YuiHub workspace.")
                servers.forEach { appendLine("nameserver $it") }
                appendLine("options edns0 trust-ad")
            }
        )
    }

    private fun ensureHosts(etcDir: File, hostname: String) {
        val hosts = File(etcDir, "hosts")
        val lines = if (hosts.isFile) hosts.readLines() else emptyList()
        val hasIpv4Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "127.0.0.1" && "localhost" in normalized.drop(1)
        }
        val hasIpv6Localhost = lines.any { line ->
            val normalized = line.substringBefore('#').trim().split(WHITESPACE_REGEX)
            normalized.firstOrNull() == "::1" && "localhost" in normalized.drop(1)
        }
        if (hasIpv4Localhost && hasIpv6Localhost) return

        hosts.parentFile?.mkdirs()
        hosts.appendText(
            buildString {
                if (hosts.exists() && hosts.length() > 0 && !hosts.readText().endsWith('\n')) {
                    appendLine()
                }
                if (!hasIpv4Localhost) {
                    append("127.0.0.1 localhost")
                    if (hostname.isNotBlank() && hostname != "localhost") {
                        append(" ")
                        append(hostname)
                    }
                    appendLine()
                }
                if (!hasIpv6Localhost) {
                    appendLine("::1 localhost ip6-localhost ip6-loopback")
                }
            }
        )
    }

    private fun ensureHostname(etcDir: File, hostname: String) {
        val target = File(etcDir, "hostname")
        if (target.isFile && target.readText().trim().isNotBlank()) return
        target.writeText("${hostname.ifBlank { DEFAULT_HOSTNAME }}\n")
    }

    private fun ensureLocale(etcDir: File, locale: String) {
        val defaultDir = File(etcDir, "default").apply { mkdirs() }
        val target = File(defaultDir, "locale")
        val lines = if (target.isFile) target.readLines().toMutableList() else mutableListOf()
        if (lines.any { it.trim().startsWith("LANG=") }) return
        lines += "LANG=$locale"
        target.writeText(lines.joinToString(separator = "\n", postfix = "\n"))
    }

    private fun ensureGroupNames(etcDir: File, groupIds: List<Long>) {
        val target = File(etcDir, "group")
        if (!target.exists()) {
            target.writeText("root:x:0:\n")
        }
        val lines = target.readLines().toMutableList()
        val existingIds = lines.mapNotNull { line ->
            line.split(':').getOrNull(2)?.toLongOrNull()
        }.toSet()
        val existingNames = lines.mapNotNull { line ->
            line.substringBefore(':').takeIf { it.isNotBlank() }
        }.toSet()
        val additions = groupIds
            .filter { it > 0 && it !in existingIds }
            .distinct()
            .map { id ->
                val baseName = "android_gid_$id"
                val name = if (baseName in existingNames) "${baseName}_workspace" else baseName
                "$name:x:$id:"
            }
        if (additions.isEmpty()) return

        target.appendText(
            buildString {
                if (target.length() > 0 && !target.readText().endsWith('\n')) {
                    appendLine()
                }
                additions.forEach { appendLine(it) }
            }
        )
    }

    private fun ensureTempDirs(linuxDir: File) {
        listOf("tmp", "var/tmp", "root").forEach { path ->
            File(linuxDir, path).mkdirs()
        }
        listOf(File(linuxDir, "tmp"), File(linuxDir, "var/tmp")).forEach { dir ->
            dir.setReadable(true, false)
            dir.setWritable(true, false)
            dir.setExecutable(true, false)
        }
        File(linuxDir, "root").apply {
            setReadable(true, true)
            setWritable(true, true)
            setExecutable(true, true)
        }
    }

    private fun currentSupplementaryGroupIds(): List<Long> {
        val status = File("/proc/self/status")
        if (!status.isFile) return emptyList()
        val groups = status.readLines().firstOrNull { it.startsWith("Groups:") } ?: return emptyList()
        return groups
            .removePrefix("Groups:")
            .trim()
            .split(WHITESPACE_REGEX)
            .mapNotNull { it.toLongOrNull() }
    }

    private companion object {
        private const val PATCH_MARKER = ".yuihub-patched"
        private const val MAX_DNS_SERVERS = 3
        private const val DEFAULT_HOSTNAME = "localhost"
        private const val APT_MIRROR_HOST = "mirrors.tuna.tsinghua.edu.cn"
        private const val APT_MIRROR = "http://mirrors.tuna.tsinghua.edu.cn/ubuntu"
        private val APT_OFFICIAL_HOSTS = listOf("archive.ubuntu.com", "security.ubuntu.com")
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val LOCAL_RESOLVERS = setOf(
            "127.0.0.1",
            "127.0.0.53",
            "::1",
        )
        private val DEFAULT_DNS_SERVERS = listOf(
            "1.1.1.1",
            "8.8.8.8",
            "223.5.5.5",
        )
    }
}

data class RootfsPatchOptions(
    val nameservers: List<String> = emptyList(),
    val hostname: String = "localhost",
    val locale: String = "C.UTF-8",
    val groupIds: List<Long> = emptyList(),
) {
    /** 参数摘要, 用于判断已 patch 的 rootfs 是否需要重新 patch */
    internal fun markerSignature(): String =
        "dns=${nameservers.sorted().joinToString(",")};host=$hostname;locale=$locale;groups=${groupIds.sorted().joinToString(",")}"
}
